<?php

/**
 * @file
 * Contains award.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function award_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the award module.
    case 'help.page.award':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Award Module') . '</p>';
      return $output;

    default:
  }
}
